// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

use crate::RepoFinderResult;
use glib::object::IsA;
use glib::translate::*;
use std::fmt;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "OstreeRepoFinder")]
    pub struct RepoFinder(Interface<ffi::OstreeRepoFinder, ffi::OstreeRepoFinderInterface>);

    match fn {
        type_ => || ffi::ostree_repo_finder_get_type(),
    }
}

impl RepoFinder {}

pub const NONE_REPO_FINDER: Option<&RepoFinder> = None;

pub trait RepoFinderExt: 'static {}

impl<O: IsA<RepoFinder>> RepoFinderExt for O {}

impl fmt::Display for RepoFinder {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("RepoFinder")
    }
}
