# This suite skips the RPMs and does the build+unit tests in a container
inherit: false

container:
  image: registry.fedoraproject.org/fedora:29
context: f29-primary
env:
  # We only use -Werror=maybe-uninitialized here with a "fixed" toolchain
  CFLAGS: '-fsanitize=undefined -fsanitize-undefined-trap-on-error -fsanitize=address -O2 -Wp,-D_FORTIFY_SOURCE=2'
  # Only for CI with a known g-ir-scanner
  GI_SCANNERFLAGS: '--warn-error'
  ASAN_OPTIONS: 'detect_leaks=0'  # Right now we're not fully clean, but this gets us use-after-free etc
  # TODO when we're doing leak checks: G_SLICE: "always-malloc"
  CONFIGOPTS: '--with-curl --with-openssl'

tests:
  - ci/ci-commitmessage-submodules.sh
  - ci/build-check.sh
  - ci/ci-release-build.sh
  - make dist-then-build

artifacts:
  - test-suite.log
  - config.log
  - gdtr-results

---
# And now the contexts below here are variant container builds

context: f29-rust
inherit: true
container:
    image: registry.fedoraproject.org/fedora:29
env:
  CONFIGOPTS: '--enable-rust'
  CI_PKGS: cargo

tests:
    - ci/build.sh
    - make check TESTS=tests/test-rollsum

---

context: f29-gnutls
inherit: true
container:
    image: registry.fedoraproject.org/fedora:29
env:
  CONFIGOPTS: '--with-crypto=gnutls'
  CI_PKGS: pkgconfig(gnutls)

tests:
    - ci/build.sh
    - make check TESTS=tests/test-basic.sh

---

inherit: true

context: f29-minimal
env:
  CONFIGOPTS: '--without-curl --without-soup --disable-gtk-doc --disable-man
   --disable-rust --without-libarchive --without-selinux --without-smack
   --without-openssl --without-avahi --without-libmount --disable-rofiles-fuse
   --disable-experimental-api'

tests:
  - ci/build.sh

---

inherit: true

context: f29-libsoup

env:
  CONFIGOPTS: "--without-curl --without-openssl --with-soup"

tests:
  - ci/build-check.sh

---

inherit: true

context: f29-introspection-tests

env:
    # ASAN conflicts with introspection testing;
    # See https://github.com/ostreedev/ostree/issues/1014
    INSTALLED_TESTS_PATTERN: "libostree/test-sizes.js libostree/test-sysroot.js libostree/test-core.js"

tests:
  - ci/build-check.sh

---

# Reset inheritance for non-variant builds
inherit: false

context: f29-flatpak

# This test case wants an "unprivileged container with bubblewrap",
# which we don't have right now; so just provision a VM and do a
# docker --privileged run.
host:
  distro: fedora/29/atomic
  specs:
    ram: 4096  # build-bundle is a static delta, which needs RAM right now

tests:
  - docker run --rm --privileged -v $(pwd):/srv/code registry.fedoraproject.org/fedora:29 /bin/sh -c "cd /srv/code && ./ci/flatpak.sh"

artifacts:
  - test-suite.log

---

# Run rpm-ostree's vmcheck.  This is a temporary hack until
# we share more code. https://github.com/projectatomic/rpm-ostree/issues/662
inherit: false

context: f29-rpmostree

cluster:
  hosts:
    - name: vmcheck
      distro: fedora/29/atomic
  container:
    image: registry.fedoraproject.org/fedora:29

env:
  HOSTS: vmcheck
  # This should roughly match the Fedora spec file, although right now we don't
  # explicitly enable gtk-doc because we don't really need it
  CONFIGOPTS: '--with-selinux --with-dracut=yesbutnoconf --with-curl --with-openssl'

tests:
  - ./ci/rpmostree.sh

artifacts:
  - test-suite.log
  - vmcheck

timeout: 60m
