site_name: OSTree
pages:
  - Home: 'index.md'
  - Contributing: 'CONTRIBUTING.md'
  - Contributing Tutorial: 'contributing-tutorial.md'
  - Manual:
      - Introduction: 'manual/introduction.md'
      - Repository: 'manual/repo.md'
      - Deployments: 'manual/deployment.md'
      - Atomic Upgrades: 'manual/atomic-upgrades.md'
      - Booting and Deployments: 'manual/boot-transaction.md'
      - Adapting Existing Systems: 'manual/adapting-existing.md'
      - Formats: 'manual/formats.md'
      - Build Systems and Repos: 'manual/buildsystem-and-repos.md'
      - Repository Management: 'manual/repository-management.md'
      - Related Projects: 'manual/related-projects.md'
