#!/bin/bash
#
# Copyright (C) 2011,2014 Colin Walters <walters@verbum.org>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

set -euo pipefail

. $(dirname $0)/libtest.sh

echo "1..17"

export OSTREE_BOOT_PARTITION="/boot"
export OSTREE_GRUB2_EXEC="builtin"
# Exports OSTREE_SYSROOT so --sysroot not needed.
setup_os_repository "archive-z2" "grub2"

. $(dirname $0)/admin-test.sh

cd ${test_tmpdir}
assert_file_has_content sysroot/boot/grub2/grub.cfg "generated by"
assert_not_file_has_content sysroot/boot/grub2/grub.cfg "assembled by"
sed -i -e 's/generated by/assembled by/' osdata/usr/lib/ostree/ostree-grub-generator
${CMD_PREFIX} ostree --repo=testos-repo commit --tree=dir=osdata/ -b testos/buildmaster/x86_64-runtime
${CMD_PREFIX} ostree admin upgrade --os=testos
assert_file_has_content sysroot/boot/grub2/grub.cfg "assembled by"
assert_not_file_has_content sysroot/boot/grub2/grub.cfg "generated by"

echo "ok updating ostree-grub-generator"
