name: ci-bootc

permissions:
  actions: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  c9s-bootc-e2e:
    runs-on: ubuntu-latest
    steps:
      # We use docker to build because it updates to the latest, whereas right now ubuntu-latest
      # has podman and buildah from ~2021 (insane!)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ci/Containerfile.c9s
          load: true
          tags: localhost/test:latest
      - name: Copy to podman
        run: sudo skopeo copy docker-daemon:localhost/test:latest containers-storage:localhost/test:latest
      - name: bootc install
        run: |
          set -xeuo pipefail
          sudo podman run --env BOOTC_SKIP_SELINUX_HOST_CHECK=1 --rm -ti --privileged -v /:/target --pid=host --security-opt label=disable \
            -v /var/lib/containers:/var/lib/containers \
            localhost/test:latest bootc install to-filesystem --skip-fetch-check \
             --replace=alongside /target
          # Verify labeling for /etc
          sudo ls -dZ /ostree/deploy/default/deploy/*.0/etc |grep :etc_t:
