// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod repo;
pub use self::repo::Repo;
pub use self::repo::RepoExt;

mod enums;
pub use self::enums::ObjectType;
pub use self::enums::RepoMode;

#[doc(hidden)]
pub mod traits {
    pub use super::RepoExt;
}
