#!/usr/bin/python

import os,sys,re,subprocess

chroot_path=sys.argv[1]

proc_path=os.path.join(chroot_path, 'proc')
subprocess.check_call(['mount', '-t', 'proc', 'proc', proc_path])

subprocess.call(['chroot', chroot_path])

subprocess.check_call(['umount', proc_path])

