#!/usr/bin/python

# Copyright (C) 2011 Colin Walters <walters@verbum.org>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import os,sys,re,subprocess

i=1
repo=sys.argv[i]
i += 1
chroot_path=sys.argv[i]
i += 1
args=sys.argv[i:]

if os.getuid() != 0:
    print "This program must be run as root."
    sys.exit(1)

rootdir=os.path.join(chroot_path, 'root')

if not os.path.isdir(rootdir):
    print "Not a directory: %s" % (rootdir, )
    sys.exit(1)

builddir = os.path.join(rootdir, 'ostree-build')
if not os.path.isdir(builddir):
    os.mkdir(builddir)


def run_in_chroot(args):
    proc_path=os.path.join(chroot_path, 'proc')
    subprocess.check_call(['mount', '-t', 'proc', 'proc', proc_path])

    try:
        subprocess.check_call(['chroot', chroot_path])
    finally:
        subprocess.call(['umount', proc_path])

run_in_chroot(args)
