// Feel free to edit this file, it won't be regenerated by gir generator unless removed.
#include <ostree.h>

// hack to build and test on versions of libostree < 2019.2
#if !OSTREE_CHECK_VERSION(2019, 2)
#  define OSTREE_REPO_LIST_REFS_EXT_EXCLUDE_MIRRORS 4
#  define OSTREE_REPO_REMOTE_CHANGE_REPLACE 4
#  define OSTREE_REPO_RESOLVE_REV_EXT_LOCAL_ONLY 1
#endif
