#!/bin/sh

start()
{
	echo -n "Starting dbus daemon: "
	mkdir -p /var/run/dbus
	/usr/bin/dbus-daemon --system
}

stop()
{
	echo -n "Stopping dbus not implemented "
	exit 1
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|condrestart}"
		;;
esac
exit $RETVAL
