#! /bin/bash

# run a GTest in tap mode. The test binary is passed as $1

srcd=$(cd $(dirname $1) && pwd)
bn=$(basename $1)
tempdir=$(mktemp -d)
function cleanup () {
    rm "${tempdir}" -rf
}
trap cleanup EXIT
cd ${tempdir}
${srcd}/${bn} -k --tap
