name: ci-bootc

permissions:
  actions: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        stream: [stream9, stream10]
    steps:
      - uses: actions/checkout@v4
      - uses: bootc-dev/actions/bootc-ubuntu-setup@main
        with:
          libvirt: true
      - name: build
        run: STREAM=${{ matrix.stream }} just build
      - name: unitcontainer
        run: STREAM=${{ matrix.stream }} just unitcontainer
      - name: unittest
        run: STREAM=${{ matrix.stream }} just unittest
      - name: integration tests (bcvk)
        timeout-minutes: 15
        run: STREAM=${{ matrix.stream }} just integration-container
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-suite-log-${{ matrix.stream }}
          path: target/unittest
